apiVersion: aws.caas.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: caas-eks
  namespace: default
spec:
  parameters:
    id: caas-eks
    region: us-west-2
    version: "1.27"
    nodes:
      count: 3
      size: small
  writeConnectionSecretToRef:
    name: caas-eks-kubeconfig
