apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xclusters.aws.caas.upbound.io
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: aws.caas.upbound.io/v1alpha1
    kind: XCluster
  resources:
    - base:
        apiVersion: aws.caas.upbound.io/v1alpha1
        kind: XNetwork
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.parameters.id
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.parameters.region
        - fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.parameters.deletionPolicy
        - fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.parameters.providerConfigName
        - fromFieldPath: spec.parameters.networkSelector
          toFieldPath: spec.compositionSelector.matchLabels[type]
        - type: ToCompositeFieldPath
          fromFieldPath: status.subnetIds
          toFieldPath: status.subnetIds
          policy:
            fromFieldPath: Required
      name: compositeNetworkEKS
    - base:
        apiVersion: aws.caas.upbound.io/v1alpha1
        kind: XEKS
      connectionDetails:
        - fromConnectionSecretKey: kubeconfig
      name: compositeClusterEKS
      patches:
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.parameters.id
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.parameters.region
        - fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.parameters.deletionPolicy
        - fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.parameters.providerConfigName
        - fromFieldPath: spec.parameters.id
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - fromFieldPath: metadata.uid
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-eks"
        - fromFieldPath: spec.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
        - fromFieldPath: spec.parameters.version
          toFieldPath: spec.parameters.version
        - fromFieldPath: spec.parameters.nodes.count
          toFieldPath: spec.parameters.nodes.count
        - fromFieldPath: spec.parameters.nodes.size
          toFieldPath: spec.parameters.nodes.size
        - fromFieldPath: status.subnetIds
          toFieldPath: spec.parameters.subnetIds
          policy:
            fromFieldPath: Required
    - base:
        apiVersion: aws.caas.upbound.io/v1alpha1
        kind: XServices
      name: compositeClusterServices
      patches:
        - fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.parameters.deletionPolicy
        - fromFieldPath: spec.parameters.id
          toFieldPath: spec.providerConfigRef.name
        - fromFieldPath: spec.parameters.services.operators.flux.version
          toFieldPath: spec.operators.flux.version
